name: grafito
summary: Grafito is a simple, self-contained web-based log viewer for journalctl
description: |
  Grafito is a simple, self-contained web-based log viewer for journalctl.
  It provides an intuitive interface to browse and filter system logs directly from your web browser.

contact: jose.masson@gmail.com
license: MIT
version: v0.9.1
confinement: strict

base: core24
adopt-info: grafito

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  grafito:
    plugin: nil
    source: https://github.com/ralsina/grafito.git
    source-type: git
    source-tag: v0.9.1
    build-snaps:
      - crystal/latest/stable
    build-packages:
      - pkg-config
      - libssl-dev
      - libpcre2-dev
    override-build: |
      make
      install -D ${CRAFT_PART_BUILD}/bin/grafito ${CRAFT_PART_INSTALL}/bin/grafito

apps:
  grafito:
    command: bin/grafito
    plugs:
    - network-bind
    - time-control
    - hardware-observe
    - mount-observe
    - network-observe
    - system-observe
